import Constants from "expo-constants";

/**
 * API Configuration
 */
export const API_CONFIG = {
  baseURL: process.env.EXPO_PUBLIC_API_URL || "http://localhost:3000/api",
  timeout: parseInt(process.env.EXPO_PUBLIC_API_TIMEOUT) || 30000,
  appVersion: Constants.expoConfig?.version || "1.0.0",
  environment: process.env.EXPO_PUBLIC_ENVIRONMENT || "development",

  // Endpoints
  endpoints: {
    auth: {
      login: "/auth/login",
      register: "/auth/register",
      logout: "/auth/logout",
      refresh: "/auth/refresh",
      resetPassword: "/auth/reset-password",
      verifyEmail: "/auth/verify-email",
    },
    projects: {
      getAll: "/projects",
      getById: (id) => `/projects/${id}`,
      create: "/projects",
      update: (id) => `/projects/${id}`,
      delete: (id) => `/projects/${id}`,
      status: (id) => `/projects/${id}/status`,
      analytics: (id) => `/projects/${id}/analytics`,
    },
    features: {
      getByProject: (projectId) => `/projects/${projectId}/features`,
      getById: (id) => `/features/${id}`,
      create: (projectId) => `/projects/${projectId}/features`,
      update: (id) => `/features/${id}`,
      delete: (id) => `/features/${id}`,
      status: (id) => `/features/${id}/status`,
      reorder: (projectId) => `/projects/${projectId}/features/reorder`,
    },
    bugs: {
      getByProject: (projectId) => `/projects/${projectId}/bugs`,
      getById: (id) => `/bugs/${id}`,
      create: (projectId) => `/projects/${projectId}/bugs`,
      update: (id) => `/bugs/${id}`,
      delete: (id) => `/bugs/${id}`,
      status: (id) => `/bugs/${id}/status`,
      assign: (id) => `/bugs/${id}/assign`,
    },
    github: {
      getRepositories: (projectId) => `/projects/${projectId}/repositories`,
      connect: (projectId) => `/projects/${projectId}/repositories`,
      disconnect: (id) => `/repositories/${id}`,
      sync: (id) => `/repositories/${id}/sync`,
      commits: (id) => `/repositories/${id}/commits`,
      branches: (id) => `/repositories/${id}/branches`,
      pullRequests: (id) => `/repositories/${id}/pull-requests`,
      issues: (id) => `/repositories/${id}/issues`,
      webhook: (id) => `/repositories/${id}/webhook`,
    },
    progress: {
      timeline: (projectId) => `/projects/${projectId}/timeline`,
      addEntry: (projectId) => `/projects/${projectId}/timeline`,
      updateEntry: (id) => `/timeline/${id}`,
      deleteEntry: (id) => `/timeline/${id}`,
      overview: (projectId) => `/projects/${projectId}/progress-overview`,
    },
    documentation: {
      getByProject: (projectId) => `/projects/${projectId}/documentation`,
      create: (projectId) => `/projects/${projectId}/documentation`,
      getById: (id) => `/documentation/${id}`,
      update: (id) => `/documentation/${id}`,
      delete: (id) => `/documentation/${id}`,
      search: (projectId) => `/projects/${projectId}/documentation/search`,
      versions: (id) => `/documentation/${id}/versions`,
    },
    knowledge: {
      getAll: "/knowledge-base",
      create: "/knowledge-base",
      getById: (id) => `/knowledge-base/${id}`,
      update: (id) => `/knowledge-base/${id}`,
      delete: (id) => `/knowledge-base/${id}`,
      search: "/knowledge-base/search",
      categories: "/knowledge-base/categories",
    },
    decisions: {
      getByProject: (projectId) => `/projects/${projectId}/decisions`,
      create: (projectId) => `/projects/${projectId}/decisions`,
      getById: (id) => `/decisions/${id}`,
      update: (id) => `/decisions/${id}`,
      delete: (id) => `/decisions/${id}`,
    },
    risks: {
      getByProject: (projectId) => `/projects/${projectId}/risks`,
      create: (projectId) => `/projects/${projectId}/risks`,
      getById: (id) => `/risks/${id}`,
      update: (id) => `/risks/${id}`,
      delete: (id) => `/risks/${id}`,
      status: (id) => `/risks/${id}/status`,
    },
    techDebt: {
      getByProject: (projectId) => `/projects/${projectId}/tech-debt`,
      create: (projectId) => `/projects/${projectId}/tech-debt`,
      getById: (id) => `/tech-debt/${id}`,
      update: (id) => `/tech-debt/${id}`,
      delete: (id) => `/tech-debt/${id}`,
      status: (id) => `/tech-debt/${id}/status`,
      overview: (projectId) => `/projects/${projectId}/tech-debt/overview`,
    },
    releases: {
      getByProject: (projectId) => `/projects/${projectId}/releases`,
      create: (projectId) => `/projects/${projectId}/releases`,
      getById: (id) => `/releases/${id}`,
      update: (id) => `/releases/${id}`,
      delete: (id) => `/releases/${id}`,
      status: (id) => `/releases/${id}/status`,
      features: (id) => `/releases/${id}/features`,
      changelog: (id) => `/releases/${id}/changelog`,
    },
    milestones: {
      getByProject: (projectId) => `/projects/${projectId}/milestones`,
      create: (projectId) => `/projects/${projectId}/milestones`,
      getById: (id) => `/milestones/${id}`,
      update: (id) => `/milestones/${id}`,
      delete: (id) => `/milestones/${id}`,
      status: (id) => `/milestones/${id}/status`,
    },
    expenses: {
      getByProject: (projectId) => `/projects/${projectId}/expenses`,
      create: (projectId) => `/projects/${projectId}/expenses`,
      getById: (id) => `/expenses/${id}`,
      update: (id) => `/expenses/${id}`,
      delete: (id) => `/expenses/${id}`,
      summary: (projectId) => `/projects/${projectId}/expenses/summary`,
      categories: (projectId) => `/projects/${projectId}/expenses/categories`,
    },
    journal: {
      getByProject: (projectId) => `/projects/${projectId}/journal`,
      create: (projectId) => `/projects/${projectId}/journal`,
      getById: (id) => `/journal/${id}`,
      update: (id) => `/journal/${id}`,
      delete: (id) => `/journal/${id}`,
      getByDate: (projectId, date) =>
        `/projects/${projectId}/journal/date/${date}`,
      stats: (projectId) => `/projects/${projectId}/journal/stats`,
    },
    ai: {
      ask: (projectId) => `/projects/${projectId}/ai/ask`,
      analyze: (projectId) => `/projects/${projectId}/ai/analyze`,
      conversations: (projectId) => `/projects/${projectId}/ai/conversations`,
      getConversation: (id) => `/ai/conversations/${id}`,
      summarize: "/ai/summarize",
      generateReport: "/ai/generate-report",
    },
    vision: {
      getAll: "/vision-board",
      create: "/vision-board",
      getById: (id) => `/vision-board/${id}`,
      update: (id) => `/vision-board/${id}`,
      delete: (id) => `/vision-board/${id}`,
      linkProject: (id) => `/vision-board/${id}/projects`,
      unlinkProject: (visionId, projectId) =>
        `/vision-board/${visionId}/projects/${projectId}`,
    },
  },
};

export default API_CONFIG;
